<?php
$releaseMetadata = release_metadata($config);
$workspaceTitles = [
    'links' => '链接管理',
    'analytics' => '访问分析',
    'marketing' => '转化分析',
    'workflows' => '个人工作流',
    'trust' => '信任与安全',
    'maintenance' => '维护',
    'webhooks' => 'Webhook',
    'audit' => '操作审计',
    'notifications' => '通知中心',
    'status' => '系统状态',
    'security' => '安全设置',
    'domains' => '域名管理',
    'api' => 'API 配置',
];
$workspaceTitle = is_logged_in() ? ($workspaceTitles[$section] ?? '管理后台') : '管理员登录';
?>
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark">
    <meta name="theme-color" content="#ffffff" data-theme-color>
    <title><?= e($workspaceTitle) ?> - 链匣 LinkVault</title>
    <script src="<?= e(asset_path('theme-init.js')) ?>"></script>
    <link rel="icon" href="<?= e(asset_path('icon.svg')) ?>" type="image/svg+xml">
    <link rel="stylesheet" href="<?= e(asset_path('app.css')) ?>">
    <script src="<?= e(asset_path('qrcode.min.js')) ?>" defer></script>
    <script src="<?= e(asset_path('app.js')) ?>" defer></script>
</head>
<body class="<?= is_logged_in() ? 'dashboard-page' : 'login-page' ?>">
<svg class="icon-sprite" aria-hidden="true" xmlns="http://www.w3.org/2000/svg">
    <symbol id="icon-link" viewBox="0 0 24 24"><path d="M9 17H7A5 5 0 0 1 7 7h2"/><path d="M15 7h2a5 5 0 1 1 0 10h-2"/><path d="M8 12h8"/></symbol>
    <symbol id="icon-moon" viewBox="0 0 24 24"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></symbol>
    <symbol id="icon-sun" viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.42"/></symbol>
    <symbol id="icon-logout" viewBox="0 0 24 24"><path d="M10 17l5-5-5-5M15 12H3M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/></symbol>
    <symbol id="icon-lock" viewBox="0 0 24 24"><rect width="18" height="11" x="3" y="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4M12 15v2"/></symbol>
    <symbol id="icon-plus" viewBox="0 0 24 24"><path d="M5 12h14M12 5v14"/></symbol>
    <symbol id="icon-gauge" viewBox="0 0 24 24"><path d="M20.38 8.53a9 9 0 1 0-.01 7M16 12l-4 4M3.6 9h2.1M18.3 9h2.1M12 3.6v2.1"/></symbol>
    <symbol id="icon-globe" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 0 1 0 20M12 2a15.3 15.3 0 0 0 0 20"/></symbol>
    <symbol id="icon-search" viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></symbol>
    <symbol id="icon-download" viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/></symbol>
    <symbol id="icon-upload" viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M17 8l-5-5-5 5M12 3v12"/></symbol>
    <symbol id="icon-copy" viewBox="0 0 24 24"><rect width="14" height="14" x="8" y="8" rx="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></symbol>
    <symbol id="icon-external" viewBox="0 0 24 24"><path d="M15 3h6v6M10 14 21 3M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></symbol>
    <symbol id="icon-power" viewBox="0 0 24 24"><path d="M12 2v10M18.4 6.6a9 9 0 1 1-12.77.04"/></symbol>
    <symbol id="icon-pencil" viewBox="0 0 24 24"><path d="M12 20h9M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z"/></symbol>
    <symbol id="icon-trash" viewBox="0 0 24 24"><path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 11v5M14 11v5"/></symbol>
    <symbol id="icon-restore" viewBox="0 0 24 24"><path d="M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5"/></symbol>
    <symbol id="icon-x" viewBox="0 0 24 24"><path d="M18 6 6 18M6 6l12 12"/></symbol>
    <symbol id="icon-save" viewBox="0 0 24 24"><path d="M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z"/><path d="M17 21v-8H7v8M7 3v5h8"/></symbol>
    <symbol id="icon-chart" viewBox="0 0 24 24"><path d="M3 3v18h18M7 16v-3M12 16V8M17 16v-5"/></symbol>
    <symbol id="icon-database" viewBox="0 0 24 24"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></symbol>
    <symbol id="icon-check-circle" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m8 12 2.6 2.6L16.5 9"/></symbol>
    <symbol id="icon-check" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></symbol>
    <symbol id="icon-alert-circle" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 8v5M12 16.5v.01"/></symbol>
    <symbol id="icon-loader" viewBox="0 0 24 24"><path d="M21 12a9 9 0 1 1-6.2-8.6"/></symbol>
    <symbol id="icon-chevron-left" viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></symbol>
    <symbol id="icon-chevron-right" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></symbol>
    <symbol id="icon-star" viewBox="0 0 24 24"><path d="m12 2.8 2.8 5.7 6.3.9-4.5 4.4 1.1 6.2-5.7-3-5.7 3 1.1-6.2-4.5-4.4 6.3-.9Z"/></symbol>
    <symbol id="icon-eye" viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></symbol>
    <symbol id="icon-share" viewBox="0 0 24 24"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/></symbol>
    <symbol id="icon-filter" viewBox="0 0 24 24"><path d="M4 5h16M7 12h10M10 19h4"/></symbol>
    <symbol id="icon-tag" viewBox="0 0 24 24"><path d="M20 13 13 20l-9-9V4h7Z"/><circle cx="8.5" cy="8.5" r="1.5"/></symbol>
    <symbol id="icon-more" viewBox="0 0 24 24"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></symbol>
    <symbol id="icon-key" viewBox="0 0 24 24"><circle cx="7.5" cy="15.5" r="5.5"/><path d="m11.5 11.5 8-8M15 8l3 3M17 6l3 3"/></symbol>
    <symbol id="icon-printer" viewBox="0 0 24 24"><path d="M6 9V3h12v6M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 14h12v7H6z"/></symbol>
    <symbol id="icon-wrench" viewBox="0 0 24 24"><path d="M14.7 6.3a4 4 0 0 0-5-5L7.6 3.4l3 3-4.2 4.2-3-3-2.1 2.1a4 4 0 0 0 5 5L16 5"/><path d="m13 11 8 8-2 2-8-8"/></symbol>
    <symbol id="icon-clipboard" viewBox="0 0 24 24"><rect width="16" height="18" x="4" y="4" rx="2"/><path d="M9 4V2h6v2M8 9h8M8 13h6M8 17h4"/></symbol>
    <symbol id="icon-settings" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/></symbol>
    <symbol id="icon-refresh" viewBox="0 0 24 24"><path d="M20 11a8 8 0 1 0-2.3 5.7M20 4v7h-7"/></symbol>
    <symbol id="icon-palette" viewBox="0 0 24 24"><path d="M12 3a9 9 0 0 0 0 18h1.5a1.5 1.5 0 0 0 0-3H12a2 2 0 0 1 0-4h4a5 5 0 0 0 0-10Z"/><circle cx="7.5" cy="10.5" r="1"/><circle cx="10" cy="7" r="1"/><circle cx="15" cy="7" r="1"/></symbol>
</svg>
<a class="skip-link" href="#main-content">跳到主要内容</a>
<header class="site-header"><div class="header-inner"><div class="brand"><span class="brand-mark" aria-hidden="true"><svg class="icon icon-lg"><use href="#icon-link"/></svg></span><div><h1>链匣 LinkVault</h1><div class="muted">你的链接，收放自如。</div></div></div><div class="header-actions"><?php if (!is_logged_in()): ?><a class="button button-secondary login-back" href="<?= e(app_path('/')) ?>" aria-label="返回首页"><svg class="icon" aria-hidden="true"><use href="#icon-chevron-left"/></svg><span>返回首页</span></a><?php endif; ?><button class="button-secondary theme-toggle" type="button" data-theme-toggle title="切换深色模式" aria-label="切换深色模式" aria-pressed="false"><svg class="icon moon-icon" aria-hidden="true"><use href="#icon-moon"/></svg><svg class="icon sun-icon" aria-hidden="true"><use href="#icon-sun"/></svg></button><?php if (is_logged_in()): ?><form method="post" action="<?= e(app_path('/logout')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><button class="button-secondary logout-button" type="submit" aria-label="退出登录" title="退出登录"><svg class="icon" aria-hidden="true"><use href="#icon-logout"/></svg><span>退出</span></button></form><?php endif; ?></div></div></header>
<main id="main-content" tabindex="-1">
<?php if (!is_logged_in()): ?>
<div class="login-shell">
<?php endif; ?>
<?php if ($flash): ?>
<?php
$flashType = (string)($flash['type'] ?? 'ok');
$flashHasRichContent = (is_string($flash['api_token'] ?? null) && $flash['api_token'] !== '')
    || (is_array($flash['recovery_codes'] ?? null) && $flash['recovery_codes'] !== [])
    || (is_string($flash['short_url'] ?? null) && $flash['short_url'] !== '')
    || (is_array($flash['undo_ids'] ?? null) && $flash['undo_ids'] !== [])
    || (is_string($flash['undo_operation_id'] ?? null) && $flash['undo_operation_id'] !== '');
$flashIsToast = $flashType !== 'error' && !$flashHasRichContent;
?>
<div class="flash <?= e($flashType) ?><?= $flashIsToast ? ' flash-toast' : '' ?>" role="<?= $flashType === 'error' ? 'alert' : 'status' ?>"<?= $flashIsToast ? ' data-toast' : '' ?><?= $flashType === 'error' ? ' data-error-focus tabindex="-1"' : '' ?>>
    <span class="flash-icon" aria-hidden="true"><svg class="icon"><use href="#icon-<?= $flash['type'] === 'error' ? 'alert' : 'check' ?>-circle"/></svg></span>
    <div class="flash-content">
        <?php if (is_string($flash['api_token'] ?? null) && $flash['api_token'] !== ''): ?>
            <div class="created-result sensitive-result" data-sensitive-result data-sensitive-label="API Token"><strong><?= e((string)$flash['message']) ?></strong><p class="sensitive-save-warning" id="api-token-save-warning">明文只显示一次。刷新或离开此页后无法找回，请先下载、打印或保存到离线密码库。</p><div class="created-link-row"><input id="created-api-token" type="text" value="<?= e($flash['api_token']) ?>" readonly aria-label="新生成的 API Token" aria-describedby="api-token-save-warning"><div class="created-link-actions"><button class="button-secondary button-small" type="button" data-copy="<?= e($flash['api_token']) ?>" data-copy-target="created-api-token"><svg class="icon" aria-hidden="true"><use href="#icon-copy"/></svg>复制 Token</button><button class="button-secondary button-small" type="button" data-sensitive-download data-sensitive-source="created-api-token" data-sensitive-filename="linkvault-api-token.txt"><svg class="icon" aria-hidden="true"><use href="#icon-download"/></svg>下载</button><button class="button-secondary button-small" type="button" data-sensitive-print data-sensitive-source="created-api-token"><svg class="icon" aria-hidden="true"><use href="#icon-printer"/></svg>打印</button></div></div><label class="offline-save-confirmation check-field"><input type="checkbox" data-offline-saved aria-describedby="api-token-save-warning"><span><strong>已离线保存</strong><small>确认已保存完整 Token 后再离开</small></span></label></div>
        <?php elseif (is_array($flash['recovery_codes'] ?? null) && $flash['recovery_codes'] !== []): ?>
            <?php $recoveryCodeText = implode("\n", array_map('strval', $flash['recovery_codes'])); ?>
            <div class="created-result sensitive-result" data-sensitive-result data-sensitive-label="管理员恢复码"><strong><?= e((string)$flash['message']) ?></strong><p class="sensitive-save-warning" id="recovery-code-save-warning">恢复码只显示一次。刷新或离开此页后无法找回，请离线保存并与数据库备份分开保管。</p><div class="created-link-row recovery-code-result"><textarea id="created-recovery-codes" rows="10" readonly aria-label="管理员恢复码" aria-describedby="recovery-code-save-warning"><?= e($recoveryCodeText) ?></textarea><div class="created-link-actions"><button class="button-secondary button-small" type="button" data-copy="<?= e($recoveryCodeText) ?>" data-copy-target="created-recovery-codes"><svg class="icon" aria-hidden="true"><use href="#icon-copy"/></svg>复制恢复码</button><button class="button-secondary button-small" type="button" data-sensitive-download data-sensitive-source="created-recovery-codes" data-sensitive-filename="linkvault-recovery-codes.txt"><svg class="icon" aria-hidden="true"><use href="#icon-download"/></svg>下载</button><button class="button-secondary button-small" type="button" data-sensitive-print data-sensitive-source="created-recovery-codes"><svg class="icon" aria-hidden="true"><use href="#icon-printer"/></svg>打印</button></div></div><label class="offline-save-confirmation check-field"><input type="checkbox" data-offline-saved aria-describedby="recovery-code-save-warning"><span><strong>已离线保存</strong><small>确认所有恢复码均已完整保存</small></span></label></div>
        <?php elseif (is_string($flash['short_url'] ?? null) && $flash['short_url'] !== ''): ?>
            <div class="created-result"><strong><?= e((string)$flash['message']) ?></strong><div class="created-link-row"><input id="created-short-url" type="text" value="<?= e($flash['short_url']) ?>" readonly aria-label="新生成的短链接"><div class="created-link-actions"><button class="button-secondary button-small" type="button" data-copy="<?= e($flash['short_url']) ?>" data-copy-target="created-short-url"><svg class="icon" aria-hidden="true"><use href="#icon-copy"/></svg>复制</button><button class="button-secondary button-small" type="button" data-share data-share-url="<?= e($flash['short_url']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-share"/></svg>分享</button><?php if (is_string($flash['detail_url'] ?? null)): ?><a class="button button-small" href="<?= e($flash['detail_url']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-eye"/></svg>详情</a><?php endif; ?></div></div></div>
        <?php else: ?>
            <?= e((string)$flash['message']) ?>
        <?php endif; ?>
        <?php if (is_array($flash['undo_ids'] ?? null) && $flash['undo_ids'] !== []): ?>
            <form class="inline-form" method="post" action="<?= e(app_path('/restore')) ?>" aria-label="撤销删除">
                <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
                <?php foreach ($flash['undo_ids'] as $undoId): ?><?php if ((int)$undoId > 0): ?><input type="hidden" name="id" value="<?= (int)$undoId ?>"><?php endif; ?><?php endforeach; ?>
                <input type="hidden" name="return_q" value="<?= e($search) ?>">
                <input type="hidden" name="return_view" value="<?= e($view) ?>">
                <input type="hidden" name="return_page" value="<?= (int)$page ?>">
                <input type="hidden" name="return_status" value="<?= e($status) ?>">
                <input type="hidden" name="return_sort" value="<?= e($sort) ?>">
                <input type="hidden" name="return_tag" value="<?= e($tag) ?>">
                <input type="hidden" name="return_favorite" value="<?= $favoritesOnly ? '1' : '' ?>">
                <button class="button-secondary button-small" type="submit">撤销删除</button>
            </form>
        <?php endif; ?>
        <?php if (is_string($flash['undo_operation_id'] ?? null) && preg_match('/^[a-f0-9]{32}$/D', $flash['undo_operation_id']) === 1): ?>
            <form class="inline-form" method="post" action="<?= e(app_path('/bulk/undo')) ?>" aria-label="撤销批量操作">
                <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
                <input type="hidden" name="operation_id" value="<?= e($flash['undo_operation_id']) ?>">
                <input type="hidden" name="return_q" value="<?= e($search) ?>"><input type="hidden" name="return_view" value="<?= e($view) ?>"><input type="hidden" name="return_page" value="<?= (int)$page ?>"><input type="hidden" name="return_status" value="<?= e($status) ?>"><input type="hidden" name="return_sort" value="<?= e($sort) ?>"><input type="hidden" name="return_tag" value="<?= e($tag) ?>"><input type="hidden" name="return_favorite" value="<?= $favoritesOnly ? '1' : '' ?>"><input type="hidden" name="return_section" value="<?= e($section) ?>"><input type="hidden" name="return_maintenance" value="<?= e($maintenanceCategory) ?>">
                <button class="button-secondary button-small" type="submit"><svg class="icon" aria-hidden="true"><use href="#icon-restore"/></svg>撤销批量操作</button>
            </form>
        <?php endif; ?>
    </div>
    <?php if ($flashIsToast): ?><button class="toast-close" type="button" data-dismiss-toast title="关闭提示" aria-label="关闭提示"><svg class="icon" aria-hidden="true"><use href="#icon-x"/></svg></button><?php endif; ?>
</div>
<?php endif; ?>

<?php if (!is_logged_in()): ?>
<section class="panel login-panel" aria-labelledby="login-heading">
    <div class="section-heading">
        <span class="section-icon" aria-hidden="true"><svg class="icon"><use href="#icon-lock"/></svg></span>
        <div><h2 id="login-heading">进入管理后台</h2><p class="muted"><?= $totpEnabled ? '输入密码和第二因素继续。' : '使用管理员密码继续。' ?></p></div>
    </div>
    <form method="post" action="<?= e(app_path('/login')) ?>">
        <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
        <label>管理密码<input type="password" name="password" autocomplete="current-password" required autofocus></label>
        <?php if ($totpEnabled): ?><label>动态口令或恢复码<input type="text" name="second_factor" autocomplete="one-time-code" autocapitalize="characters" maxlength="20" required></label><?php endif; ?>
        <button type="submit"><svg class="icon" aria-hidden="true"><use href="#icon-lock"/></svg>安全登录</button>
    </form>
</section>
</div>
<?php else: ?>
<?php
$renderReturnContext = static function () use ($search, $view, $page, $status, $sort, $tag, $favoritesOnly, $section, $maintenanceCategory): void {
    ?>
    <input type="hidden" name="return_q" value="<?= e($search) ?>">
    <input type="hidden" name="return_view" value="<?= e($view) ?>">
    <input type="hidden" name="return_page" value="<?= (int)$page ?>">
    <input type="hidden" name="return_status" value="<?= e($status) ?>">
    <input type="hidden" name="return_sort" value="<?= e($sort) ?>">
    <input type="hidden" name="return_tag" value="<?= e($tag) ?>">
    <input type="hidden" name="return_favorite" value="<?= $favoritesOnly ? '1' : '' ?>">
    <input type="hidden" name="return_section" value="<?= e($section) ?>">
    <input type="hidden" name="return_maintenance" value="<?= e($maintenanceCategory) ?>">
    <?php
};
?>
<div class="app-shell">
<nav class="primary-nav" aria-label="管理工作区">
    <span class="primary-nav-label">管理工作区</span>
    <a href="<?= e(app_path('/')) ?>"<?= $section === 'links' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-link"/></svg><span>链接</span></a>
    <a href="<?= e(list_path('', 'active', 1, 'all', 'created_desc', '', false, 0, 'analytics')) ?>"<?= $section === 'analytics' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-chart"/></svg><span>访问分析</span></a>
    <a href="<?= e(app_path('/?section=marketing')) ?>"<?= $section === 'marketing' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-chart"/></svg><span>转化</span></a>
    <a href="<?= e(app_path('/?section=workflows')) ?>"<?= $section === 'workflows' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-settings"/></svg><span>工作流</span></a>
    <a data-advanced-capability href="<?= e(app_path('/?section=trust')) ?>"<?= $section === 'trust' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-alert-circle"/></svg><span>信任与安全</span></a>
    <a href="<?= e(list_path('', 'active', 1, 'all', 'created_desc', '', false, 0, 'maintenance')) ?>"<?= $section === 'maintenance' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-wrench"/></svg><span>维护</span></a>
    <a data-advanced-capability href="<?= e(list_path('', 'active', 1, 'all', 'created_desc', '', false, 0, 'webhooks')) ?>"<?= $section === 'webhooks' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-share"/></svg><span>Webhook</span></a>
    <a data-advanced-capability href="<?= e(list_path('', 'active', 1, 'all', 'created_desc', '', false, 0, 'audit')) ?>"<?= $section === 'audit' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-clipboard"/></svg><span>审计</span></a>
    <a data-advanced-capability href="<?= e(app_path('/?section=notifications')) ?>"<?= $section === 'notifications' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-alert-circle"/></svg><span>通知<?= $adminNotifications['unread'] > 0 ? '（' . (int)$adminNotifications['unread'] . '）' : '' ?></span></a>
    <a data-advanced-capability href="<?= e(list_path('', 'active', 1, 'all', 'created_desc', '', false, 0, 'status')) ?>"<?= $section === 'status' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-gauge"/></svg><span>系统状态</span></a>
    <a data-advanced-capability href="<?= e(list_path('', 'active', 1, 'all', 'created_desc', '', false, 0, 'security')) ?>"<?= $section === 'security' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-lock"/></svg><span>安全</span></a>
    <a data-advanced-capability href="<?= e(list_path('', 'active', 1, 'all', 'created_desc', '', false, 0, 'domains')) ?>"<?= $section === 'domains' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-globe"/></svg><span>域名</span></a>
    <a data-advanced-capability href="<?= e(list_path('', 'active', 1, 'all', 'created_desc', '', false, 0, 'api')) ?>"<?= $section === 'api' ? ' aria-current="page"' : '' ?>><svg class="icon" aria-hidden="true"><use href="#icon-key"/></svg><span>API 配置</span></a>
    <span class="capability-mode" role="group" aria-label="能力模式"><button type="button" data-capability-mode="basic">基础</button><button type="button" data-capability-mode="advanced">高级</button></span>
    <button class="button-secondary command-trigger" type="button" data-command-open title="打开快捷命令"><svg class="icon" aria-hidden="true"><use href="#icon-search"/></svg><span>命令</span><kbd>Ctrl K</kbd></button>
</nav>
<div class="app-content">
<?php if ($undoableBulkOperations): ?>
<aside class="bulk-undo-center" aria-label="可撤销的批量操作">
    <div><strong>可撤销操作</strong><span class="muted">操作应用后 24 小时内有效</span></div>
    <div class="bulk-undo-list">
        <?php foreach ($undoableBulkOperations as $undoableOperation): ?>
            <form method="post" action="<?= e(app_path('/bulk/undo')) ?>">
                <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="operation_id" value="<?= e($undoableOperation['id']) ?>"><?php $renderReturnContext(); ?>
                <span><strong><?= e($undoableOperation['action_label']) ?> <?= (int)$undoableOperation['changed'] ?> 条</strong><small>截止 <time datetime="<?= e(gmdate('Y-m-d\TH:i:s\Z', $undoableOperation['undo_expires_at'])) ?>" data-local-time><?= e(gmdate('Y-m-d\TH:i:s\Z', $undoableOperation['undo_expires_at'])) ?> UTC</time></small></span>
                <button class="button-secondary button-small" type="submit"><svg class="icon" aria-hidden="true"><use href="#icon-restore"/></svg>撤销</button>
            </form>
        <?php endforeach; ?>
    </div>
</aside>
<?php endif; ?>
<?php if ($section === 'links'): ?>
<section class="workspace-grid">
    <div class="panel creator-panel">
        <div class="section-heading"><span class="section-icon" aria-hidden="true"><svg class="icon"><use href="#icon-plus"/></svg></span><div><h2>创建短链接</h2><div class="muted">输入目标地址，可按需设置短码和有效期。</div></div></div>
        <?php if ($duplicateLinks): ?><div class="duplicate-warning"><strong>已有 <?= count($duplicateLinks) ?> 条相同目标地址</strong><?php foreach ($duplicateLinks as $duplicate): ?><?php $duplicateUrl = short_url_base($config, $duplicate) . '/' . rawurlencode((string)$duplicate['slug']); $duplicateStatusKey = valid_slug((string)$duplicate['slug']) ? link_status_key($duplicate) : 'unavailable'; $duplicateStatusLabel = valid_slug((string)$duplicate['slug']) ? link_status_label($duplicate) : '不可访问'; ?><div><span class="duplicate-link-info"><a href="<?= e(app_path('/link') . '?id=' . (int)$duplicate['id']) ?>"><?= e($duplicateUrl) ?></a><span class="status <?= e($duplicateStatusKey) ?>"><?= e($duplicateStatusLabel) ?></span></span><button class="button-secondary icon-button button-small" type="button" data-copy="<?= e($duplicateUrl) ?>" title="复制已有短链接" aria-label="复制已有短链接"><svg class="icon" aria-hidden="true"><use href="#icon-copy"/></svg></button></div><?php endforeach; ?></div><?php endif; ?>
        <div class="preset-toolbar"><label><span class="sr-only">创建预设</span><select data-link-preset><option value="">选择创建预设</option><?php foreach ($linkPresets as $preset): ?><option value="<?= (int)$preset['id'] ?>" data-values="<?= e(json_encode($preset['values'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)) ?>"><?= e((string)$preset['name']) ?></option><?php endforeach; ?></select></label><button class="button-secondary" type="button" data-apply-preset disabled>应用</button><details><summary class="button button-secondary">保存当前设置</summary><div class="preset-save-fields"><label>预设名称<input type="text" maxlength="60" required data-preset-name></label><label>默认有效期（天）<input type="number" min="0" max="3650" value="0" data-preset-days><span class="field-note">0 表示不限期</span></label><button type="button" data-save-preset-trigger><svg class="icon"><use href="#icon-save"/></svg>保存预设</button></div></details></div><span class="field-error" data-preset-error role="alert" hidden></span>
        <?php if ($linkPresets): ?><div class="preset-list"><?php foreach ($linkPresets as $preset): ?><span><strong><?= e((string)$preset['name']) ?></strong><form method="post" action="<?= e(app_path('/presets/delete')) ?>" data-confirm="确认删除这个创建预设？"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$preset['id'] ?>"><button class="icon-button button-secondary button-small" type="submit" title="删除预设 <?= e((string)$preset['name']) ?>" aria-label="删除预设 <?= e((string)$preset['name']) ?>"><svg class="icon"><use href="#icon-x"/></svg></button></form></span><?php endforeach; ?></div><?php endif; ?>
        <form class="form-grid" id="create-link-form" method="post" action="<?= e(app_path('/shorten')) ?>" data-preserve-draft="create-link">
            <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="create_request_id" value="<?= e($createRequestId) ?>"><?php if ($duplicateLinks && $duplicateTargetHash !== ''): ?><input type="hidden" name="allow_duplicate" value="1"><input type="hidden" name="duplicate_target_hash" value="<?= e($duplicateTargetHash) ?>"><?php endif; ?><?php if (isset($createErrors['request'])): ?><div class="field-error field-wide" id="create-request-error"><?= e((string)$createErrors['request']) ?></div><?php endif; ?>
            <label class="field-wide">原始链接<input type="url" name="target_url" value="<?= e($createValues['target_url']) ?>" maxlength="<?= (int)($config['target_url_max_length'] ?? 2048) ?>" placeholder="https://example.com/long/path" required<?= isset($createErrors['target_url']) ? ' aria-invalid="true" aria-describedby="create-target-url-error"' : '' ?>><?php if (isset($createErrors['target_url'])): ?><span class="field-error" id="create-target-url-error"><?= e((string)$createErrors['target_url']) ?></span><?php endif; ?></label>
            <label class="field-wide">标题，可选<input type="text" name="title" value="<?= e($createValues['title']) ?>" maxlength="120" placeholder="方便自己识别"<?= isset($createErrors['title']) ? ' aria-invalid="true" aria-describedby="create-title-error"' : '' ?>><?php if (isset($createErrors['title'])): ?><span class="field-error" id="create-title-error"><?= e((string)$createErrors['title']) ?></span><?php endif; ?></label>
            <?php $advancedCreateOpen = (bool)array_filter(array_diff_key($createValues, ['target_url' => true, 'title' => true, 'one_time_mode' => true])) || (bool)array_diff_key($createErrors, ['target_url' => true, 'title' => true, 'request' => true]); ?>
            <details class="advanced-options advanced-create field-wide"<?= $advancedCreateOpen ? ' open' : '' ?>><summary><svg class="icon" aria-hidden="true"><use href="#icon-settings"/></svg>高级创建</summary><div class="advanced-grid">
            <label>自定义短码，可选<input type="text" name="custom_slug" value="<?= e($createValues['custom_slug']) ?>" pattern="[A-Za-z0-9_\-]{3,64}" placeholder="例如 docs2026"<?= isset($createErrors['custom_slug']) ? ' aria-invalid="true" aria-describedby="create-custom-slug-error"' : '' ?>><?php if (isset($createErrors['custom_slug'])): ?><span class="field-error" id="create-custom-slug-error"><?= e((string)$createErrors['custom_slug']) ?></span><?php endif; ?></label>
            <?php if ($shortDomains): ?><label>短链域名<select name="short_domain_id"<?= isset($createErrors['short_domain_id']) ? ' aria-invalid="true" aria-describedby="create-short-domain-error"' : '' ?>><option value="">默认域名</option><?php foreach ($shortDomains as $domainOption): ?><?php if ($domainOption['verified_at'] !== null && (int)$domainOption['is_enabled'] === 1): ?><option value="<?= (int)$domainOption['id'] ?>"<?= $createValues['short_domain_id'] === (string)$domainOption['id'] ? ' selected' : '' ?>><?= e((string)$domainOption['hostname']) ?></option><?php endif; ?><?php endforeach; ?></select><?php if (isset($createErrors['short_domain_id'])): ?><span class="field-error" id="create-short-domain-error"><?= e((string)$createErrors['short_domain_id']) ?></span><?php endif; ?></label><?php endif; ?>
            <label class="field-wide">标签，可选<input type="text" name="tags" value="<?= e($createValues['tags']) ?>" maxlength="260" placeholder="工作, 文档, 稍后阅读"<?= isset($createErrors['tags']) ? ' aria-invalid="true" aria-describedby="create-tags-error"' : '' ?>><?php if (isset($createErrors['tags'])): ?><span class="field-error" id="create-tags-error"><?= e((string)$createErrors['tags']) ?></span><?php endif; ?></label>
            <details class="advanced-options campaign-options field-wide"<?= array_filter([$createValues['campaign_name'], $createValues['campaign_source'], $createValues['campaign_medium'], $createValues['campaign_content']]) || array_intersect_key($createErrors, array_flip(['campaign_name', 'campaign_source', 'campaign_medium', 'campaign_content'])) ? ' open' : '' ?>><summary>广告活动归因</summary><div class="advanced-grid"><label>活动名称<input type="text" name="campaign_name" value="<?= e($createValues['campaign_name']) ?>" maxlength="100" placeholder="例如 summer_launch"<?= isset($createErrors['campaign_name']) ? ' aria-invalid="true" aria-describedby="create-campaign-name-error"' : '' ?>><?php if (isset($createErrors['campaign_name'])): ?><span class="field-error" id="create-campaign-name-error"><?= e((string)$createErrors['campaign_name']) ?></span><?php endif; ?></label><label>来源<input type="text" name="campaign_source" value="<?= e($createValues['campaign_source']) ?>" maxlength="100" placeholder="例如 newsletter"<?= isset($createErrors['campaign_source']) ? ' aria-invalid="true" aria-describedby="create-campaign-source-error"' : '' ?>><?php if (isset($createErrors['campaign_source'])): ?><span class="field-error" id="create-campaign-source-error"><?= e((string)$createErrors['campaign_source']) ?></span><?php endif; ?></label><label>媒介<input type="text" name="campaign_medium" value="<?= e($createValues['campaign_medium']) ?>" maxlength="100" placeholder="例如 email"<?= isset($createErrors['campaign_medium']) ? ' aria-invalid="true" aria-describedby="create-campaign-medium-error"' : '' ?>><?php if (isset($createErrors['campaign_medium'])): ?><span class="field-error" id="create-campaign-medium-error"><?= e((string)$createErrors['campaign_medium']) ?></span><?php endif; ?></label><label>内容<input type="text" name="campaign_content" value="<?= e($createValues['campaign_content']) ?>" maxlength="100" placeholder="例如 hero_button"<?= isset($createErrors['campaign_content']) ? ' aria-invalid="true" aria-describedby="create-campaign-content-error"' : '' ?>><?php if (isset($createErrors['campaign_content'])): ?><span class="field-error" id="create-campaign-content-error"><?= e((string)$createErrors['campaign_content']) ?></span><?php endif; ?></label><span class="field-note field-wide">保存时自动生成 utm_campaign、utm_source、utm_medium 和 utm_content。</span></div></details>
            <fieldset class="field-wide expiration-field"><legend>过期时间，可选（<span data-timezone-label>UTC</span>）</legend><div class="preset-row" role="group" aria-label="有效期快捷选项"><button class="button-secondary button-small" type="button" data-expiration-days="1">1 天</button><button class="button-secondary button-small" type="button" data-expiration-days="7">7 天</button><button class="button-secondary button-small" type="button" data-expiration-days="30">30 天</button><button class="button-secondary button-small" type="button" data-expiration-clear>不限</button></div><input type="datetime-local" name="expires_at" value="<?= e($createValues['expires_at']) ?>" aria-label="过期时间" data-expiration-input<?= isset($createErrors['expires_at']) ? ' aria-invalid="true" aria-describedby="create-expires-at-error"' : '' ?>><input type="hidden" name="expires_at_offset" value="0" data-expiration-offset><?php if (isset($createErrors['expires_at'])): ?><span class="field-error" id="create-expires-at-error"><?= e((string)$createErrors['expires_at']) ?></span><?php endif; ?></fieldset>
            <details class="advanced-options field-wide"<?= $createValues['starts_at'] !== '' || $createValues['max_clicks'] !== '' || $createValues['is_one_time'] !== '' ? ' open' : '' ?>><summary>高级有效期</summary><div class="advanced-grid"><label>定时启用（<span data-timezone-label>UTC</span>）<input type="datetime-local" name="starts_at" value="<?= e($createValues['starts_at']) ?>" data-start-input<?= isset($createErrors['starts_at']) ? ' aria-invalid="true" aria-describedby="create-starts-at-error"' : '' ?>><input type="hidden" name="starts_at_offset" value="0" data-start-offset><?php if (isset($createErrors['starts_at'])): ?><span class="field-error" id="create-starts-at-error"><?= e((string)$createErrors['starts_at']) ?></span><?php endif; ?></label><label>最大点击次数<input type="number" name="max_clicks" value="<?= e($createValues['max_clicks']) ?>" min="1" max="2147483647" inputmode="numeric" placeholder="不限"<?= isset($createErrors['max_clicks']) ? ' aria-invalid="true" aria-describedby="create-max-clicks-error"' : '' ?>><?php if (isset($createErrors['max_clicks'])): ?><span class="field-error" id="create-max-clicks-error"><?= e((string)$createErrors['max_clicks']) ?></span><?php endif; ?></label><label class="check-field"><input type="checkbox" name="is_one_time" value="1"<?= $createValues['is_one_time'] === '1' ? ' checked' : '' ?>>一次性链接</label><label>一次性消费方式<select name="one_time_mode"><option value="immediate"<?= $createValues['one_time_mode'] === 'immediate' ? ' selected' : '' ?>>首次访问即消费</option><option value="confirm"<?= $createValues['one_time_mode'] === 'confirm' ? ' selected' : '' ?>>确认访问后消费</option></select></label><label class="check-field"><input type="checkbox" name="is_favorite" value="1"<?= $createValues['is_favorite'] === '1' ? ' checked' : '' ?>>创建后收藏</label></div></details>
            <details class="advanced-options field-wide"<?= $createValues['access_password_required'] !== '' || $createValues['invalid_message'] !== '' || $createValues['fallback_url'] !== '' || array_intersect_key($createErrors, array_flip(['access_password', 'invalid_message', 'fallback_url'])) ? ' open' : '' ?>><summary>访问保护与失效处理</summary><div class="advanced-grid"><label>访问密码，可选<?php if ($createValues['access_password_required'] !== ''): ?><input type="hidden" name="access_password_required" value="1"><?php endif; ?><input type="password" name="access_password" maxlength="1024" autocomplete="new-password"<?= $createValues['access_password_required'] !== '' ? ' required' : '' ?><?= isset($createErrors['access_password']) ? ' aria-invalid="true" aria-describedby="create-access-password-error"' : '' ?>><?php if (isset($createErrors['access_password'])): ?><span class="field-error" id="create-access-password-error"><?= e((string)$createErrors['access_password']) ?></span><?php endif; ?></label><label>失效后备用地址，可选<input type="url" name="fallback_url" value="<?= e($createValues['fallback_url']) ?>" maxlength="<?= (int)($config['target_url_max_length'] ?? 2048) ?>" placeholder="https://example.com/fallback"<?= isset($createErrors['fallback_url']) ? ' aria-invalid="true" aria-describedby="create-fallback-url-error"' : '' ?>><?php if (isset($createErrors['fallback_url'])): ?><span class="field-error" id="create-fallback-url-error"><?= e((string)$createErrors['fallback_url']) ?></span><?php endif; ?></label><label class="field-wide">失效提示，可选<textarea name="invalid_message" maxlength="500" rows="3"<?= isset($createErrors['invalid_message']) ? ' aria-invalid="true" aria-describedby="create-invalid-message-error"' : '' ?>><?= e($createValues['invalid_message']) ?></textarea><?php if (isset($createErrors['invalid_message'])): ?><span class="field-error" id="create-invalid-message-error"><?= e((string)$createErrors['invalid_message']) ?></span><?php endif; ?></label></div></details>
            </div></details>
            <button class="form-submit" type="submit"><svg class="icon" aria-hidden="true"><use href="#icon-plus"/></svg><?= $duplicateLinks ? '继续创建新短链' : '生成短链接' ?></button>
        </form>
    </div>
    <form id="save-link-preset-form" method="post" action="<?= e(app_path('/presets/save')) ?>" data-save-preset hidden><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="name" data-preset-submit-name><input type="hidden" name="expires_days" data-preset-submit-days><?php foreach (['short_domain_id', 'tags', 'max_clicks', 'is_one_time', 'one_time_mode', 'campaign_name', 'campaign_source', 'campaign_medium', 'campaign_content', 'fallback_url', 'invalid_message'] as $presetField): ?><input type="hidden" name="<?= e($presetField) ?>" data-preset-value="<?= e($presetField) ?>"><?php endforeach; ?></form>
    <aside class="panel overview-panel" aria-label="服务概览"><div class="overview-heading"><div class="section-heading"><span class="section-icon" aria-hidden="true"><svg class="icon"><use href="#icon-gauge"/></svg></span><h2>概览</h2></div><span class="live-status">服务可访问</span></div><div class="metric-grid"><div class="metric"><span>当前视图</span><strong><?= $totalLinks ?></strong><small>条链接</small></div><div class="metric"><span>当前视图近 14 日</span><strong data-overview-total>--</strong><small>次跳转</small></div></div><div class="endpoint"><div class="endpoint-label"><svg class="icon" aria-hidden="true"><use href="#icon-globe"/></svg>服务地址</div><code title="<?= e($baseUrl) ?>"><?= e($baseUrl) ?></code></div><div class="quick-create"><div class="endpoint-label"><svg class="icon" aria-hidden="true"><use href="#icon-plus"/></svg>快速创建</div><button class="button button-secondary" type="button" data-copy="<?= e($bookmarklet) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-copy"/></svg>复制书签脚本</button><code>POST <?= e(app_path('/api/shorten')) ?></code><span class="muted">API Token：<?= $apiTokenEnabled ? '已启用' : '未配置' ?></span></div></aside>
</section>

<?php if (is_array($importPreview)): ?>
<?php
$importModeLabels = ['skip' => '冲突时跳过', 'overwrite' => '冲突时覆盖', 'new_slug' => '冲突时生成新短码'];
$importActionLabels = ['insert' => '新增', 'renamed' => '生成新短码', 'overwrite' => '覆盖'];
$importFieldLabels = [
    'slug' => '短码', 'target_url' => '目标地址', 'title' => '标题', 'is_active' => '启用状态',
    'expires_at' => '过期时间', 'is_favorite' => '收藏', 'starts_at' => '启用时间',
    'max_clicks' => '点击上限', 'is_one_time' => '一次性链接', 'one_time_mode' => '消费方式',
    'campaign_name' => '活动名称', 'campaign_source' => '活动来源', 'campaign_medium' => '活动媒介',
    'campaign_content' => '活动内容', 'password_protected' => '密码保护',
    'access_password_reset_required' => '须重设密码',
    'invalid_message' => '失效提示', 'fallback_url' => '备用地址',
    'short_domain' => '短链域名', 'tags' => '标签',
];
$formatImportValue = static function (mixed $value): string {
    if ($value === null || $value === '') {
        return '（空）';
    }
    return is_array($value) ? ($value ? implode(', ', array_map('strval', $value)) : '（空）') : (string)$value;
};
?>
<section class="panel import-preview-panel">
    <div class="stats-heading"><span class="section-heading"><span class="section-icon"><svg class="icon"><use href="#icon-upload"/></svg></span><h2>导入预览 / Dry Run</h2></span><span class="muted"><?= e($importModeLabels[(string)($importPreview['mode'] ?? 'skip')] ?? '冲突时跳过') ?> · 预览 15 分钟内有效</span></div>
    <div class="preview-counts"><div><strong><?= (int)$importPreview['new'] ?></strong><span>新增</span></div><div><strong><?= (int)$importPreview['renamed'] ?></strong><span>新短码</span></div><div><strong><?= (int)$importPreview['overwritten'] ?></strong><span>覆盖</span></div><div><strong><?= (int)$importPreview['unchanged'] ?></strong><span>无变化</span></div><div><strong><?= (int)$importPreview['duplicate'] ?></strong><span>跳过</span></div><div><strong><?= (int)$importPreview['invalid'] ?></strong><span>无效</span></div></div>
    <?php if ((int)$importPreview['change_count'] > 0): ?>
        <div class="preview-changes">
            <p class="muted">前 <?= min(100, (int)$importPreview['change_count']) ?> / 共 <?= (int)$importPreview['change_count'] ?> 项写入差异</p>
            <div class="table-scroll" role="region" aria-label="导入差异，可横向滚动" tabindex="0"><table><thead><tr><th>行</th><th>操作</th><th>短码</th><th>字段差异</th></tr></thead><tbody><?php foreach ($importPreview['changes'] as $change): ?><tr><td data-label="行"><?= (int)$change['row'] ?></td><td data-label="操作"><?= e($importActionLabels[(string)$change['action']] ?? (string)$change['action']) ?><?= !empty($change['deleted']) ? '<br><span class="field-error">保留回收站状态</span>' : '' ?></td><td data-label="短码"><?= e((string)$change['source_slug']) ?><?php if ((string)$change['source_slug'] !== (string)$change['result_slug']): ?><br><span class="muted">→ <?= e((string)$change['result_slug']) ?></span><?php endif; ?></td><td data-label="字段差异"><details><summary><?= count($change['diffs'] ?? []) ?> 个字段</summary><dl class="import-diff-list"><?php foreach ($change['diffs'] ?? [] as $diff): ?><div><dt><?= e($importFieldLabels[(string)$diff['field']] ?? (string)$diff['field']) ?></dt><dd><del><?= e($formatImportValue($diff['before'] ?? null)) ?></del><span aria-hidden="true">→</span><ins><?= e($formatImportValue($diff['after'] ?? null)) ?></ins></dd></div><?php endforeach; ?></dl></details></td></tr><?php endforeach; ?></tbody></table></div>
        </div>
    <?php endif; ?>
    <?php if ((int)$importPreview['issue_count'] > 0): ?>
        <div class="preview-errors">
            <p class="muted">前 <?= min(100, (int)$importPreview['issue_count']) ?> / 共 <?= (int)$importPreview['issue_count'] ?> 条问题（共 <?= (int)$importPreview['total'] ?> 条记录）</p>
            <table><thead><tr><th>行</th><th>短码</th><th>结果</th></tr></thead><tbody><?php foreach ($importPreview['issues'] as $issue): ?><tr><td data-label="行"><?= (int)$issue['row'] ?></td><td data-label="短码"><?= e((string)$issue['slug']) ?></td><td data-label="结果"><?= e((string)$issue['reason']) ?></td></tr><?php endforeach; ?></tbody></table>
        </div>
    <?php endif; ?>
    <div class="preview-actions">
        <form method="post" action="<?= e(app_path('/import-confirm')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="preview_token" value="<?= e((string)$importPreview['token']) ?>"><button type="submit"<?= (int)$importPreview['writes'] === 0 ? ' disabled' : '' ?>><svg class="icon"><use href="#icon-upload"/></svg>确认应用 <?= (int)$importPreview['writes'] ?> 项</button></form>
        <form method="post" action="<?= e(app_path('/import-cancel')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><button class="button-secondary" type="submit">取消</button></form>
        <?php if ((int)$importPreview['issue_count'] > 0): ?><a class="button button-secondary" href="<?= e(app_path('/import-report')) ?>" download><svg class="icon" aria-hidden="true"><use href="#icon-download"/></svg>下载完整错误报告</a><?php endif; ?>
        <?php if ((int)$importPreview['change_count'] > 0): ?><a class="button button-secondary" href="<?= e(app_path('/import-report?type=changes')) ?>" download><svg class="icon" aria-hidden="true"><use href="#icon-download"/></svg>下载完整差异</a><?php endif; ?>
    </div>
</section>
<?php endif; ?>

<section class="panel list-panel list-panel-spaced">
    <div class="saved-filter-bar">
        <div class="saved-filter-list" aria-label="常用筛选">
            <span class="muted">常用筛选</span>
            <?php foreach ($savedFilters as $savedFilter): ?>
                <span class="saved-filter-item"><a href="<?= e(list_path((string)$savedFilter['search'], (string)$savedFilter['view'], 1, (string)$savedFilter['status'], (string)$savedFilter['sort'], (string)$savedFilter['tag'], (int)$savedFilter['favorites_only'] === 1)) ?>"><?= e((string)$savedFilter['name']) ?></a><button class="icon-button button-secondary button-small" type="button" data-rename-filter data-filter-id="<?= (int)$savedFilter['id'] ?>" data-filter-name="<?= e((string)$savedFilter['name']) ?>" title="重命名常用筛选 <?= e((string)$savedFilter['name']) ?>" aria-label="重命名常用筛选 <?= e((string)$savedFilter['name']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-pencil"/></svg></button><form method="post" action="<?= e(app_path('/filters/delete')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$savedFilter['id'] ?>"><?php $renderReturnContext(); ?><button class="icon-button button-secondary button-small" type="submit" title="删除常用筛选 <?= e((string)$savedFilter['name']) ?>" aria-label="删除常用筛选 <?= e((string)$savedFilter['name']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-x"/></svg></button></form></span>
            <?php endforeach; ?>
        </div>
        <form class="save-filter-form" method="post" action="<?= e(app_path('/filters/save')) ?>">
            <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="q" value="<?= e($search) ?>"><input type="hidden" name="view" value="<?= e($view) ?>"><input type="hidden" name="status" value="<?= e($status) ?>"><input type="hidden" name="sort" value="<?= e($sort) ?>"><input type="hidden" name="tag" value="<?= e($tag) ?>"><input type="hidden" name="favorite" value="<?= $favoritesOnly ? '1' : '' ?>"><?php $renderReturnContext(); ?>
            <label><span class="sr-only">常用筛选名称</span><input type="text" name="name" maxlength="60" placeholder="筛选名称" required></label><button class="button-secondary" type="submit"><svg class="icon"><use href="#icon-save"/></svg>保存筛选</button>
        </form>
    </div>
    <dialog id="rename-filter-dialog" aria-labelledby="rename-filter-title">
        <form class="rename-filter-form" method="post" action="<?= e(app_path('/filters/rename')) ?>">
            <div class="dialog-header"><span class="dialog-title"><svg class="icon" aria-hidden="true"><use href="#icon-pencil"/></svg><h2 id="rename-filter-title">重命名常用筛选</h2></span><button class="button-secondary icon-button" type="button" data-close-dialog title="关闭重命名窗口" aria-label="关闭重命名窗口"><svg class="icon" aria-hidden="true"><use href="#icon-x"/></svg></button></div>
            <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="" data-rename-filter-id><?php $renderReturnContext(); ?>
            <label for="rename-filter-name">筛选名称<input id="rename-filter-name" type="text" name="name" maxlength="60" required data-rename-filter-name></label>
            <div class="dialog-actions"><button class="button-secondary" type="button" data-close-dialog>取消</button><button type="submit"><svg class="icon" aria-hidden="true"><use href="#icon-save"/></svg>保存名称</button></div>
        </form>
    </dialog>
    <div class="toolbar">
        <form class="filter-form" method="get" action="<?= e(app_path('/')) ?>"><?php if ($view === 'trash'): ?><input type="hidden" name="view" value="trash"><?php endif; ?><label class="search-field"><span class="sr-only">搜索链接</span><svg class="icon" aria-hidden="true"><use href="#icon-search"/></svg><input type="search" name="q" value="<?= e($search) ?>" placeholder="搜索标题、短码、标签或目标域名"></label><?php if ($view !== 'trash'): ?><label class="compact-field"><span class="sr-only">状态</span><select name="status" aria-label="状态筛选"><option value="all"<?= $status === 'all' ? ' selected' : '' ?>>全部状态</option><option value="active"<?= $status === 'active' ? ' selected' : '' ?>>启用中</option><option value="inactive"<?= $status === 'inactive' ? ' selected' : '' ?>>已停用</option><option value="scheduled"<?= $status === 'scheduled' ? ' selected' : '' ?>>待启用</option><option value="expired"<?= $status === 'expired' ? ' selected' : '' ?>>已过期</option><option value="exhausted"<?= $status === 'exhausted' ? ' selected' : '' ?>>次数用尽</option></select></label><?php endif; ?><label class="compact-field"><span class="sr-only">标签</span><select name="tag" aria-label="标签筛选"><option value="">全部标签</option><?php foreach ($allTags as $tagOption): ?><option value="<?= e((string)$tagOption['tag']) ?>"<?= $tag === (string)$tagOption['tag'] ? ' selected' : '' ?>><?= e((string)$tagOption['tag']) ?> (<?= (int)$tagOption['link_count'] ?>)</option><?php endforeach; ?></select></label><label class="compact-field"><span class="sr-only">排序</span><select name="sort" aria-label="链接排序"><option value="created_desc"<?= $sort === 'created_desc' ? ' selected' : '' ?>>最新创建</option><option value="created_asc"<?= $sort === 'created_asc' ? ' selected' : '' ?>>最早创建</option><option value="clicks_desc"<?= $sort === 'clicks_desc' ? ' selected' : '' ?>>点击最多</option><option value="clicks_asc"<?= $sort === 'clicks_asc' ? ' selected' : '' ?>>点击最少</option><option value="last_accessed_desc"<?= $sort === 'last_accessed_desc' ? ' selected' : '' ?>>最近访问</option><option value="title_asc"<?= $sort === 'title_asc' ? ' selected' : '' ?>>标题 A-Z</option></select></label><?php if ($view !== 'trash'): ?><label class="check-field filter-favorite"><input type="checkbox" name="favorite" value="1"<?= $favoritesOnly ? ' checked' : '' ?>>仅收藏</label><?php endif; ?><button type="submit"><svg class="icon" aria-hidden="true"><use href="#icon-filter"/></svg>筛选</button><?php if ($hasFilters): ?><a class="button button-secondary" href="<?= e(list_path('', $view, 1, 'all', $sort)) ?>">清除筛选</a><?php endif; ?></form>
        <details class="data-tools"><summary class="button button-secondary"><svg class="icon" aria-hidden="true"><use href="#icon-more"/></svg>数据工具</summary><div class="toolbar-actions"><div class="export-scope-actions" role="group" aria-label="导出范围"><a class="button button-secondary" href="<?= e(app_path('/export-links')) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-download"/></svg>导出全部链接</a><a class="button button-secondary" href="<?= e(app_path('/export-links') . '?' . $currentExportQuery) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-filter"/></svg>导出当前筛选</a></div><a class="button button-secondary icon-button" href="<?= e(app_path('/export-snapshot')) ?>" title="审计数据快照（不可恢复）" aria-label="审计数据快照（不可恢复）"><svg class="icon" aria-hidden="true"><use href="#icon-database"/></svg></a><form class="import-form" method="post" action="<?= e(app_path('/import')) ?>" enctype="multipart/form-data" data-import-form><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><label class="import-mode">冲突策略<select name="conflict_mode"><option value="skip">跳过</option><option value="overwrite">覆盖现有链接</option><option value="new_slug">生成新短码</option></select></label><label class="file-input"><span class="button button-secondary"><svg class="icon" aria-hidden="true"><use href="#icon-upload"/></svg>选择 JSON</span><input type="file" name="import_file" accept="application/json,.json" required data-import-file></label><div class="file-selection"><span class="file-summary" data-file-summary aria-live="polite">未选择文件</span><button class="button-secondary icon-button file-clear" type="button" data-file-clear title="清除已选择的文件" aria-label="清除已选择的导入文件" hidden><svg class="icon" aria-hidden="true"><use href="#icon-x"/></svg></button></div><div class="import-progress" data-import-progress hidden><progress max="100" value="0" aria-label="导入文件上传进度"></progress><span data-import-progress-label aria-live="polite">准备上传</span></div><button type="submit" data-import-preview disabled>预览导入</button></form></div></details>
    </div>
    <nav class="tabs" aria-label="链接视图"><a class="<?= $view === 'active' ? 'selected' : '' ?>" href="<?= e(list_path($search, 'active', 1, $status, $sort, $tag, $favoritesOnly)) ?>"<?= $view === 'active' ? ' aria-current="page"' : '' ?>>链接<?= $view === 'active' ? '（' . $totalLinks . '）' : '' ?></a><a class="<?= $view === 'trash' ? 'selected' : '' ?>" href="<?= e(list_path($search, 'trash', 1, 'all', $sort, $tag)) ?>"<?= $view === 'trash' ? ' aria-current="page"' : '' ?>>回收站</a></nav>
    <div class="list-heading"><div><h2><?= $view === 'trash' ? '回收站' : '链接列表' ?></h2><span class="muted">共 <?= $totalLinks ?> 条，每页 <?= $pageSize ?> 条</span></div><?php if ($links): ?><form id="bulk-form" class="bulk-form" method="post" action="<?= e(app_path('/bulk')) ?>" data-bulk-form data-bulk-preview-action="<?= e(app_path('/bulk/preview')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="q" value="<?= e($search) ?>"><input type="hidden" name="view" value="<?= e($view) ?>"><input type="hidden" name="status" value="<?= e($status) ?>"><input type="hidden" name="sort" value="<?= e($sort) ?>"><input type="hidden" name="tag" value="<?= e($tag) ?>"><input type="hidden" name="favorite" value="<?= $favoritesOnly ? '1' : '' ?>"><input type="hidden" name="return_q" value="<?= e($search) ?>"><input type="hidden" name="return_view" value="<?= e($view) ?>"><input type="hidden" name="return_page" value="<?= $page ?>"><input type="hidden" name="return_status" value="<?= e($status) ?>"><input type="hidden" name="return_sort" value="<?= e($sort) ?>"><input type="hidden" name="return_tag" value="<?= e($tag) ?>"><input type="hidden" name="return_favorite" value="<?= $favoritesOnly ? '1' : '' ?>"><input type="hidden" name="confirm_purge" value="" data-bulk-purge-confirm><span class="muted" data-selected-count aria-live="polite">已选择 0 条</span><button class="button-secondary" type="submit" formaction="<?= e(app_path('/export-links')) ?>" formmethod="post" formnovalidate data-selected-export disabled><svg class="icon"><use href="#icon-download"/></svg>导出所选</button><select name="bulk_action" aria-label="批量操作" required data-bulk-action><option value="">批量操作</option><?php if ($view === 'trash'): ?><option value="restore">恢复</option><option value="purge">永久删除</option><?php else: ?><option value="favorite">收藏</option><option value="unfavorite">取消收藏</option><option value="enable">启用</option><option value="disable">停用</option><option value="delete">移入回收站</option><?php endif; ?></select><button class="button-secondary" type="submit" data-bulk-submit disabled>预览影响</button></form><?php endif; ?></div>
    <?php if (!$links): ?><?php if ($hasFilters): ?><div class="empty">没有匹配的链接。<div class="muted"><?= e((string)$filterDescription) ?></div><a class="button button-secondary button-small" href="<?= e(list_path('', $view, 1, 'all', $sort)) ?>">清除筛选</a></div><?php else: ?><div class="empty"><?= $view === 'trash' ? '回收站为空。' : '还没有短链接。' ?></div><?php endif; ?><?php else: ?>
    <div class="selected-link-tools"><button class="button-secondary button-small" type="button" data-selected-copy disabled><svg class="icon"><use href="#icon-copy"/></svg>复制所选短链接</button><span class="muted">每条链接单独一行，方便粘贴到文档或发布工具</span></div>
    <div class="table-scroll link-table-scroll" role="region" aria-label="链接列表，可横向滚动" tabindex="0"><table class="link-table"><thead><tr><th class="column-select"><input type="checkbox" data-select-all aria-label="选择本页全部链接"></th><th class="column-short">短链接</th><th>目标链接</th><th class="column-clicks">跳转次数</th><th class="column-actions">操作</th></tr></thead><tbody>
    <?php $links = (static function (array $items, array $config, string &$rowBaseUrl): Generator { foreach ($items as $item) { $rowBaseUrl = short_url_base($config, $item); yield $item; } })($links, $config, $baseUrl); ?>
    <?php foreach ($links as $link): ?><?php $shortUrl = $baseUrl . '/' . rawurlencode((string)$link['slug']); $statusKey = link_status_key($link); $expirationUtc = is_string($link['expires_at'] ?? null) ? $link['expires_at'] : ''; $startsUtc = is_string($link['starts_at'] ?? null) ? $link['starts_at'] : ''; $linkTags = split_stored_tags((string)$link['tags']); $isFailedEdit = $failedEditId === (int)$link['id']; $editErrors = $isFailedEdit ? $failedEditErrors : []; $editTargetUrl = $isFailedEdit && is_string($failedEditValues['target_url'] ?? null) ? $failedEditValues['target_url'] : (string)$link['target_url']; $editTitle = $isFailedEdit && is_string($failedEditValues['title'] ?? null) ? $failedEditValues['title'] : (string)$link['title']; $editExpiration = $isFailedEdit && is_string($failedEditValues['expires_at'] ?? null) ? $failedEditValues['expires_at'] : expiration_input_value($expirationUtc); $editStarts = $isFailedEdit && is_string($failedEditValues['starts_at'] ?? null) ? $failedEditValues['starts_at'] : expiration_input_value($startsUtc); $editTags = $isFailedEdit && is_string($failedEditValues['tags'] ?? null) ? $failedEditValues['tags'] : format_tags_input($linkTags); $editMaxClicks = $isFailedEdit && is_string($failedEditValues['max_clicks'] ?? null) ? $failedEditValues['max_clicks'] : ($link['max_clicks'] === null ? '' : (string)$link['max_clicks']); $editFavorite = $isFailedEdit ? (($failedEditValues['is_favorite'] ?? '') === '1') : ((int)$link['is_favorite'] === 1); $editOneTime = $isFailedEdit ? (($failedEditValues['is_one_time'] ?? '') === '1') : ((int)$link['is_one_time'] === 1); $editOneTimeMode = $isFailedEdit && is_string($failedEditValues['one_time_mode'] ?? null) ? $failedEditValues['one_time_mode'] : (string)($link['one_time_mode'] ?? 'immediate'); $editCampaignName = $isFailedEdit && is_string($failedEditValues['campaign_name'] ?? null) ? $failedEditValues['campaign_name'] : (string)($link['campaign_name'] ?? ''); $editCampaignSource = $isFailedEdit && is_string($failedEditValues['campaign_source'] ?? null) ? $failedEditValues['campaign_source'] : (string)($link['campaign_source'] ?? ''); $editCampaignMedium = $isFailedEdit && is_string($failedEditValues['campaign_medium'] ?? null) ? $failedEditValues['campaign_medium'] : (string)($link['campaign_medium'] ?? ''); $editCampaignContent = $isFailedEdit && is_string($failedEditValues['campaign_content'] ?? null) ? $failedEditValues['campaign_content'] : (string)($link['campaign_content'] ?? ''); $dialogShouldOpen = $requestedEditId === (int)$link['id']; ?>
    <tr><td class="column-select" data-label="选择"><input type="checkbox" name="selected[]" value="<?= (int)$link['id'] ?>" form="bulk-form" data-row-select aria-label="选择 <?= e((string)$link['slug']) ?>"></td><td data-label="短链接"><div class="short-link-heading"><?php if ((int)$link['is_favorite'] === 1): ?><svg class="icon favorite-icon" aria-label="已收藏"><use href="#icon-star"/></svg><?php endif; ?><span class="short-url"><a id="short-url-<?= (int)$link['id'] ?>" href="<?= e($shortUrl) ?>" target="_blank" rel="noopener"><?= e($shortUrl) ?></a></span></div><span class="status <?= e($statusKey) ?>"><?= e(link_status_label($link)) ?></span><?php if ($link['title'] !== ''): ?><div class="link-title"><?= e((string)$link['title']) ?></div><?php endif; ?><div class="tag-list"><?php foreach ($linkTags as $linkTag): ?><a class="tag-chip" href="<?= e(list_path('', $view, 1, 'all', $sort, $linkTag)) ?>"><?= e($linkTag) ?></a><?php endforeach; ?></div></td><td data-label="目标链接"><a class="target-url" href="<?= e((string)$link['target_url']) ?>" target="_blank" rel="noopener"><?= e((string)$link['target_url']) ?></a><div class="muted">创建：<time datetime="<?= e((string)$link['created_at']) ?>" data-local-time><?= e((string)$link['created_at']) ?> UTC</time></div><?php if ($startsUtc !== ''): ?><div class="muted">启用：<time datetime="<?= e($startsUtc) ?>" data-local-time><?= e($startsUtc) ?> UTC</time></div><?php endif; ?><?php if ($expirationUtc !== ''): ?><div class="muted">过期：<time datetime="<?= e($expirationUtc) ?>" data-local-time><?= e($expirationUtc) ?> UTC</time></div><?php endif; ?></td><td data-label="跳转次数"><strong><?= (int)$link['clicks'] ?></strong><?php if ($link['max_clicks'] !== null || (int)$link['is_one_time'] === 1): ?><span class="muted"> / <?= (int)$link['is_one_time'] === 1 ? 1 : (int)$link['max_clicks'] ?></span><?php endif; ?><div class="muted">近 7 个 UTC 自然日 <?= (int)$link['recent_clicks'] ?> 次</div><div class="muted">最后跳转：<?php if (!empty($link['last_accessed_at'])): ?><time datetime="<?= e((string)$link['last_accessed_at']) ?>" data-local-time><?= e((string)$link['last_accessed_at']) ?> UTC</time><?php else: ?>暂无<?php endif; ?></div></td>
    <td data-label="操作"><div class="actions">
        <?php if ($view === 'trash'): ?>
            <button class="button-secondary button-small icon-button" type="button" data-copy="<?= e($shortUrl) ?>" data-copy-target="short-url-<?= (int)$link['id'] ?>" title="复制 <?= e((string)$link['slug']) ?>" aria-label="复制 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-copy"/></svg></button>
            <a class="button button-secondary button-small icon-button" href="<?= e(app_path('/link') . '?id=' . (int)$link['id']) ?>" title="查看详情 <?= e((string)$link['slug']) ?>" aria-label="查看详情 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-eye"/></svg></a>
            <?php if (link_is_password_protected($link)): ?><span class="access-indicator" title="需要访问密码"><svg class="icon" aria-hidden="true"><use href="#icon-lock"/></svg><span>已保护</span></span><?php endif; ?>
            <form class="desktop-secondary-action" method="post" action="<?= e(app_path('/restore')) ?>">
                <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
                <input type="hidden" name="id" value="<?= (int)$link['id'] ?>">
                <?php $renderReturnContext(); ?>
                <button class="button-secondary button-small" type="submit" aria-label="恢复 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-restore"/></svg>恢复</button>
            </form>
            <form class="desktop-secondary-action" method="post" action="<?= e(app_path('/purge')) ?>" data-purge-form data-purge-slug="<?= e((string)$link['slug']) ?>" data-purge-title="<?= e($link['title'] !== '' ? (string)$link['title'] : '未命名') ?>" data-confirm-token="<?= e(purge_confirmation_token((int)$link['id'])) ?>">
                <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
                <input type="hidden" name="id" value="<?= (int)$link['id'] ?>">
                <input type="hidden" name="confirmation_token" value="" data-confirmation-token>
                <?php $renderReturnContext(); ?>
                <button class="button-danger button-small" type="submit" aria-label="永久删除 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-trash"/></svg>永久删除</button>
            </form>
            <details class="mobile-action-menu"><summary class="button button-secondary button-small icon-button" title="更多操作 <?= e((string)$link['slug']) ?>" aria-label="更多操作 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-more"/></svg></summary><div class="mobile-action-menu-items">
                <form method="post" action="<?= e(app_path('/restore')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$link['id'] ?>"><?php $renderReturnContext(); ?><button class="button-secondary button-small" type="submit" aria-label="恢复 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-restore"/></svg>恢复</button></form>
                <form method="post" action="<?= e(app_path('/purge')) ?>" data-purge-form data-purge-slug="<?= e((string)$link['slug']) ?>" data-purge-title="<?= e($link['title'] !== '' ? (string)$link['title'] : '未命名') ?>" data-confirm-token="<?= e(purge_confirmation_token((int)$link['id'])) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$link['id'] ?>"><input type="hidden" name="confirmation_token" value="" data-confirmation-token><?php $renderReturnContext(); ?><button class="button-danger button-small" type="submit" aria-label="永久删除 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-trash"/></svg>永久删除</button></form>
            </div></details>
        <?php else: ?>
            <form class="desktop-secondary-action" method="post" action="<?= e(app_path('/favorite')) ?>">
                <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
                <input type="hidden" name="id" value="<?= (int)$link['id'] ?>">
                <input type="hidden" name="desired_state" value="<?= (int)$link['is_favorite'] === 1 ? '0' : '1' ?>">
                <?php $renderReturnContext(); ?>
                <button class="button-secondary button-small icon-button" type="submit" title="<?= (int)$link['is_favorite'] === 1 ? '取消收藏 ' : '收藏 ' ?><?= e((string)$link['slug']) ?>" aria-label="<?= (int)$link['is_favorite'] === 1 ? '取消收藏 ' : '收藏 ' ?><?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-star"/></svg></button>
            </form>
            <button class="button-secondary button-small icon-button" type="button" data-copy="<?= e($shortUrl) ?>" data-copy-target="short-url-<?= (int)$link['id'] ?>" title="复制 <?= e((string)$link['slug']) ?>" aria-label="复制 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-copy"/></svg></button>
            <button class="button-secondary button-small icon-button desktop-secondary-action" type="button" data-share data-share-url="<?= e(short_url_base($config, $link) . '/' . rawurlencode((string)$link['slug'])) ?>" data-share-title="<?= e((string)$link['title']) ?>" data-copy-target="short-url-<?= (int)$link['id'] ?>" title="分享 <?= e((string)$link['slug']) ?>" aria-label="分享 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-share"/></svg></button>
            <a class="button button-secondary button-small icon-button" href="<?= e(app_path('/link') . '?id=' . (int)$link['id']) ?>" title="查看详情 <?= e((string)$link['slug']) ?>" aria-label="查看详情 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-eye"/></svg></a>
            <?php if (link_is_password_protected($link)): ?><span class="access-indicator" title="需要访问密码"><svg class="icon" aria-hidden="true"><use href="#icon-lock"/></svg><span>已保护</span></span><?php endif; ?>
            <?php if ($statusKey === 'expired'): ?>
                <form class="desktop-secondary-action" method="post" action="<?= e(app_path('/clear-expiration')) ?>">
                    <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
                    <input type="hidden" name="id" value="<?= (int)$link['id'] ?>">
                    <?php $renderReturnContext(); ?>
                    <button class="button-secondary button-small" type="submit" aria-label="清除过期时间 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-restore"/></svg>清除过期时间</button>
                </form>
            <?php else: ?>
                <form class="desktop-secondary-action" method="post" action="<?= e(app_path('/toggle')) ?>">
                    <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
                    <input type="hidden" name="id" value="<?= (int)$link['id'] ?>">
                    <input type="hidden" name="desired_state" value="<?= (int)$link['is_active'] === 1 ? '0' : '1' ?>">
                    <input type="hidden" name="updated_at" value="<?= e((string)$link['updated_at']) ?>">
                    <?php $renderReturnContext(); ?>
                    <button class="button-secondary button-small" type="submit" aria-label="<?= (int)$link['is_active'] === 1 ? '停用 ' : '启用 ' ?><?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-power"/></svg><?= (int)$link['is_active'] === 1 ? '停用' : '启用' ?></button>
                </form>
            <?php endif; ?>
            <a class="button button-secondary button-small icon-button desktop-secondary-action" href="<?= e(edit_path($search, $view, $page, (int)$link['id'], $status, $sort, $tag, $favoritesOnly)) ?>" title="编辑 <?= e((string)$link['slug']) ?>" aria-label="编辑 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-pencil"/></svg></a>
    <dialog id="edit-<?= (int)$link['id'] ?>" aria-labelledby="edit-title-<?= (int)$link['id'] ?>"<?= $dialogShouldOpen ? ' open data-auto-open' : '' ?>>
        <form class="edit-form" method="post" action="<?= e(app_path('/edit')) ?>">
            <div class="dialog-header"><span class="dialog-title"><svg class="icon"><use href="#icon-pencil"/></svg><h2 id="edit-title-<?= (int)$link['id'] ?>">编辑短链接：<?= e((string)$link['slug']) ?></h2></span><a class="button button-secondary" href="<?= e(list_path($search, $view, $page, $status, $sort, $tag, $favoritesOnly)) ?>" data-close-dialog title="关闭 <?= e((string)$link['slug']) ?> 编辑窗口" aria-label="关闭 <?= e((string)$link['slug']) ?> 编辑窗口"><svg class="icon" aria-hidden="true"><use href="#icon-x"/></svg></a></div>
            <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">
            <input type="hidden" name="id" value="<?= (int)$link['id'] ?>">
            <input type="hidden" name="updated_at" value="<?= e((string)$link['updated_at']) ?>">
            <?php $renderReturnContext(); ?>
            <label>短码<input type="text" value="<?= e((string)$link['slug']) ?>" readonly></label>
            <label>目标链接<input type="url" name="target_url" value="<?= e($editTargetUrl) ?>" maxlength="<?= (int)($config['target_url_max_length'] ?? 2048) ?>" required<?= isset($editErrors['target_url']) ? ' aria-invalid="true" aria-describedby="edit-target-url-error-' . (int)$link['id'] . '"' : '' ?>><?php if (isset($editErrors['target_url'])): ?><span class="field-error" id="edit-target-url-error-<?= (int)$link['id'] ?>"><?= e((string)$editErrors['target_url']) ?></span><?php endif; ?></label>
            <div class="form-row">
                <label>标题<input type="text" name="title" value="<?= e($editTitle) ?>" maxlength="120"<?= isset($editErrors['title']) ? ' aria-invalid="true" aria-describedby="edit-title-error-' . (int)$link['id'] . '"' : '' ?>><?php if (isset($editErrors['title'])): ?><span class="field-error" id="edit-title-error-<?= (int)$link['id'] ?>"><?= e((string)$editErrors['title']) ?></span><?php endif; ?></label>
                <label>标签<input type="text" name="tags" value="<?= e($editTags) ?>" maxlength="260"<?= isset($editErrors['tags']) ? ' aria-invalid="true" aria-describedby="edit-tags-error-' . (int)$link['id'] . '"' : '' ?>><?php if (isset($editErrors['tags'])): ?><span class="field-error" id="edit-tags-error-<?= (int)$link['id'] ?>"><?= e((string)$editErrors['tags']) ?></span><?php endif; ?></label>
            </div>
            <div class="form-row">
                <label>定时启用<input type="datetime-local" name="starts_at" value="<?= e($editStarts) ?>" data-start-input<?= !$isFailedEdit && $startsUtc !== '' ? ' data-utc-value="' . e($startsUtc) . '"' : '' ?><?= isset($editErrors['starts_at']) ? ' aria-invalid="true" aria-describedby="edit-starts-at-error-' . (int)$link['id'] . '"' : '' ?>><input type="hidden" name="starts_at_offset" value="0" data-start-offset><?php if (isset($editErrors['starts_at'])): ?><span class="field-error" id="edit-starts-at-error-<?= (int)$link['id'] ?>"><?= e((string)$editErrors['starts_at']) ?></span><?php endif; ?></label>
                <label>过期时间<input type="datetime-local" name="expires_at" value="<?= e($editExpiration) ?>" data-expiration-input<?= !$isFailedEdit && $expirationUtc !== '' ? ' data-utc-value="' . e($expirationUtc) . '"' : '' ?><?= isset($editErrors['expires_at']) ? ' aria-invalid="true" aria-describedby="edit-expires-at-error-' . (int)$link['id'] . '"' : '' ?>><input type="hidden" name="expires_at_offset" value="0" data-expiration-offset><?php if (isset($editErrors['expires_at'])): ?><span class="field-error" id="edit-expires-at-error-<?= (int)$link['id'] ?>"><?= e((string)$editErrors['expires_at']) ?></span><?php endif; ?></label>
            </div>
            <div class="form-row">
                <label>最大点击次数<input type="number" name="max_clicks" value="<?= e($editMaxClicks) ?>" min="1" max="2147483647"<?= isset($editErrors['max_clicks']) ? ' aria-invalid="true" aria-describedby="edit-max-clicks-error-' . (int)$link['id'] . '"' : '' ?>><?php if (isset($editErrors['max_clicks'])): ?><span class="field-error" id="edit-max-clicks-error-<?= (int)$link['id'] ?>"><?= e((string)$editErrors['max_clicks']) ?></span><?php endif; ?></label>
                <label>一次性消费方式<select name="one_time_mode"><option value="immediate"<?= $editOneTimeMode === 'immediate' ? ' selected' : '' ?>>首次访问即消费</option><option value="confirm"<?= $editOneTimeMode === 'confirm' ? ' selected' : '' ?>>确认访问后消费</option></select></label>
            </div>
            <fieldset class="edit-campaign-fields"><legend>广告活动归因</legend><div class="form-row"><label>活动名称<input type="text" name="campaign_name" value="<?= e($editCampaignName) ?>" maxlength="100"<?= isset($editErrors['campaign_name']) ? ' aria-invalid="true"' : '' ?>><?php if (isset($editErrors['campaign_name'])): ?><span class="field-error"><?= e((string)$editErrors['campaign_name']) ?></span><?php endif; ?></label><label>来源<input type="text" name="campaign_source" value="<?= e($editCampaignSource) ?>" maxlength="100"<?= isset($editErrors['campaign_source']) ? ' aria-invalid="true"' : '' ?>><?php if (isset($editErrors['campaign_source'])): ?><span class="field-error"><?= e((string)$editErrors['campaign_source']) ?></span><?php endif; ?></label></div><div class="form-row"><label>媒介<input type="text" name="campaign_medium" value="<?= e($editCampaignMedium) ?>" maxlength="100"<?= isset($editErrors['campaign_medium']) ? ' aria-invalid="true"' : '' ?>><?php if (isset($editErrors['campaign_medium'])): ?><span class="field-error"><?= e((string)$editErrors['campaign_medium']) ?></span><?php endif; ?></label><label>内容<input type="text" name="campaign_content" value="<?= e($editCampaignContent) ?>" maxlength="100"<?= isset($editErrors['campaign_content']) ? ' aria-invalid="true"' : '' ?>><?php if (isset($editErrors['campaign_content'])): ?><span class="field-error"><?= e((string)$editErrors['campaign_content']) ?></span><?php endif; ?></label></div></fieldset>
            <fieldset class="edit-access-fields"><legend>访问保护与失效处理</legend><div class="form-row"><label>设置新访问密码<input type="password" name="access_password" maxlength="1024" autocomplete="new-password" placeholder="留空则保持不变"<?= isset($editErrors['access_password']) ? ' aria-invalid="true" aria-describedby="edit-access-password-error-' . (int)$link['id'] . '"' : '' ?>><?php if (isset($editErrors['access_password'])): ?><span class="field-error" id="edit-access-password-error-<?= (int)$link['id'] ?>"><?= e((string)$editErrors['access_password']) ?></span><?php endif; ?></label><label>失效后备用地址<input type="url" name="fallback_url" value="<?= e($isFailedEdit && is_string($failedEditValues['fallback_url'] ?? null) ? $failedEditValues['fallback_url'] : (string)($link['fallback_url'] ?? '')) ?>" maxlength="<?= (int)($config['target_url_max_length'] ?? 2048) ?>"<?= isset($editErrors['fallback_url']) ? ' aria-invalid="true"' : '' ?>><?php if (isset($editErrors['fallback_url'])): ?><span class="field-error"><?= e((string)$editErrors['fallback_url']) ?></span><?php endif; ?></label></div><label>失效提示<textarea name="invalid_message" maxlength="500" rows="3"<?= isset($editErrors['invalid_message']) ? ' aria-invalid="true"' : '' ?>><?= e($isFailedEdit && is_string($failedEditValues['invalid_message'] ?? null) ? $failedEditValues['invalid_message'] : (string)($link['invalid_message'] ?? '')) ?></textarea><?php if (isset($editErrors['invalid_message'])): ?><span class="field-error"><?= e((string)$editErrors['invalid_message']) ?></span><?php endif; ?></label><label class="check-field"><input type="checkbox" name="remove_access_password" value="1"<?= $isFailedEdit && ($failedEditValues['remove_access_password'] ?? '') === '1' ? ' checked' : '' ?>>移除现有访问密码<?= link_is_password_protected($link) ? '' : '（当前未设置）' ?></label></fieldset>
            <div class="check-stack"><label class="check-field"><input type="checkbox" name="is_one_time" value="1"<?= $editOneTime ? ' checked' : '' ?>>一次性链接</label><label class="check-field"><input type="checkbox" name="is_favorite" value="1"<?= $editFavorite ? ' checked' : '' ?>>收藏</label></div>
            <button type="submit"><svg class="icon"><use href="#icon-save"/></svg>保存修改</button>
        </form>
    </dialog>
    <form class="desktop-secondary-action" method="post" action="<?= e(app_path('/delete')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$link['id'] ?>"><?php $renderReturnContext(); ?><button class="button-danger button-small icon-button" type="submit" title="移入回收站 <?= e((string)$link['slug']) ?>" aria-label="移入回收站 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-trash"/></svg></button></form>
    <details class="mobile-action-menu"><summary class="button button-secondary button-small icon-button" title="更多操作 <?= e((string)$link['slug']) ?>" aria-label="更多操作 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-more"/></svg></summary><div class="mobile-action-menu-items">
        <form method="post" action="<?= e(app_path('/favorite')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$link['id'] ?>"><input type="hidden" name="desired_state" value="<?= (int)$link['is_favorite'] === 1 ? '0' : '1' ?>"><?php $renderReturnContext(); ?><button class="button-secondary button-small" type="submit" aria-label="<?= (int)$link['is_favorite'] === 1 ? '取消收藏 ' : '收藏 ' ?><?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-star"/></svg><?= (int)$link['is_favorite'] === 1 ? '取消收藏' : '收藏' ?></button></form>
        <button class="button-secondary button-small" type="button" data-share data-share-url="<?= e(short_url_base($config, $link) . '/' . rawurlencode((string)$link['slug'])) ?>" data-share-title="<?= e((string)$link['title']) ?>" data-copy-target="short-url-<?= (int)$link['id'] ?>" aria-label="分享 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-share"/></svg>分享</button>
        <?php if ($statusKey === 'expired'): ?>
            <form method="post" action="<?= e(app_path('/clear-expiration')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$link['id'] ?>"><?php $renderReturnContext(); ?><button class="button-secondary button-small" type="submit" aria-label="清除过期时间 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-restore"/></svg>清除过期时间</button></form>
        <?php else: ?>
            <form method="post" action="<?= e(app_path('/toggle')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$link['id'] ?>"><input type="hidden" name="desired_state" value="<?= (int)$link['is_active'] === 1 ? '0' : '1' ?>"><input type="hidden" name="updated_at" value="<?= e((string)$link['updated_at']) ?>"><?php $renderReturnContext(); ?><button class="button-secondary button-small" type="submit" aria-label="<?= (int)$link['is_active'] === 1 ? '停用 ' : '启用 ' ?><?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-power"/></svg><?= (int)$link['is_active'] === 1 ? '停用' : '启用' ?></button></form>
        <?php endif; ?>
        <a class="button button-secondary button-small" href="<?= e(edit_path($search, $view, $page, (int)$link['id'], $status, $sort, $tag, $favoritesOnly)) ?>" aria-label="编辑 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-pencil"/></svg>编辑</a>
        <form method="post" action="<?= e(app_path('/delete')) ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$link['id'] ?>"><?php $renderReturnContext(); ?><button class="button-danger button-small" type="submit" aria-label="移入回收站 <?= e((string)$link['slug']) ?>"><svg class="icon" aria-hidden="true"><use href="#icon-trash"/></svg>移入回收站</button></form>
    </div></details><?php endif; ?></div></td></tr>
    <?php endforeach; ?></tbody></table></div><?php $lastPage = max(1, (int)ceil($totalLinks / $pageSize)); if ($totalLinks > $pageSize): ?><div class="pagination"><?php if ($page > 1): ?><a class="button button-secondary button-small" href="<?= e(list_path($search, $view, $page - 1, $status, $sort, $tag, $favoritesOnly)) ?>"><svg class="icon"><use href="#icon-chevron-left"/></svg>上一页</a><?php endif; ?><span class="muted">第 <?= $page ?> / <?= $lastPage ?> 页</span><?php if ($page < $lastPage): ?><a class="button button-secondary button-small" href="<?= e(list_path($search, $view, $page + 1, $status, $sort, $tag, $favoritesOnly)) ?>">下一页<svg class="icon"><use href="#icon-chevron-right"/></svg></a><?php endif; ?></div><?php endif; ?><?php endif; ?>
</section>
<section class="panel stats-panel stats-placeholder" data-overview-url="<?= e($overviewUrl) ?>" aria-live="polite">
    <div class="stats-heading"><span class="section-heading"><span class="section-icon"><svg class="icon"><use href="#icon-chart"/></svg></span><h2>当前视图近 14 日跳转统计</h2></span><span class="muted">正在加载...</span></div>
</section>
<?php elseif ($section === 'analytics'): ?>
<?php require __DIR__ . '/analytics.php'; ?>
<?php elseif (in_array($section, ['marketing', 'workflows', 'trust'], true)): ?>
<?php require __DIR__ . '/p2_workspaces.php'; ?>
<?php elseif ($section === 'maintenance'): ?>
<?php require __DIR__ . '/maintenance.php'; ?>
<?php elseif ($section === 'webhooks'): ?>
<?php require __DIR__ . '/webhook_center.php'; ?>
<?php elseif ($section === 'audit'): ?>
<?php require __DIR__ . '/audit.php'; ?>
<?php elseif ($section === 'notifications'): ?>
<?php require __DIR__ . '/notification_center.php'; ?>
<?php elseif (in_array($section, ['status', 'security', 'domains', 'api'], true)): ?>
<?php require __DIR__ . '/system_status.php'; ?>
<?php endif; ?>
</div>
</div>
<?php endif; ?>
</main>
<?php if (is_logged_in()): ?>
<dialog class="command-dialog" data-command-dialog aria-labelledby="command-title">
    <div class="command-shell"><div class="command-search"><svg class="icon" aria-hidden="true"><use href="#icon-search"/></svg><label class="sr-only" for="command-query">搜索命令</label><input id="command-query" type="search" placeholder="搜索命令" autocomplete="off" data-command-query><button class="icon-button button-secondary" type="button" data-command-close aria-label="关闭快捷命令" title="关闭"><svg class="icon"><use href="#icon-x"/></svg></button></div><h2 id="command-title" class="sr-only">快捷命令</h2><div class="command-list" data-command-list><a href="<?= e(app_path('/')) ?>" data-command-item data-command-terms="create new link 创建 新链接">创建链接</a><a href="<?= e(app_path('/?section=workflows')) ?>" data-command-item data-command-terms="workflow tags duplicates 工作流 标签 重复">工作流与重复合并</a><a href="<?= e(app_path('/?section=marketing')) ?>" data-command-item data-command-terms="marketing funnel conversion 转化 漏斗">转化与漏斗</a><a href="<?= e(app_path('/?section=trust')) ?>" data-command-item data-command-terms="trust report blacklist scan 安全 举报 黑名单 扫描">信任与安全</a><a href="<?= e(app_path('/?section=api')) ?>" data-command-item data-command-terms="api token">API Token</a><a href="<?= e(app_path('/?section=analytics')) ?>" data-command-item data-command-terms="analytics 分析">访问分析</a></div></div>
</dialog>
<dialog class="bulk-preview-dialog" data-bulk-preview-dialog aria-labelledby="bulk-preview-title" aria-describedby="bulk-preview-description">
    <div class="bulk-preview-content">
        <div class="dialog-header"><span class="dialog-title"><svg class="icon" aria-hidden="true"><use href="#icon-eye"/></svg><h2 id="bulk-preview-title">批量操作影响预览</h2></span><button class="button-secondary icon-button" type="button" data-bulk-preview-cancel title="关闭影响预览" aria-label="关闭影响预览"><svg class="icon" aria-hidden="true"><use href="#icon-x"/></svg></button></div>
        <div class="bulk-preview-body"><p id="bulk-preview-description" class="muted" data-bulk-preview-description>确认后才会修改链接。</p><div class="preview-counts"><div><strong data-bulk-preview-change>0</strong><span>将变更</span></div><div><strong data-bulk-preview-unchanged>0</strong><span>无需变更</span></div><div><strong data-bulk-preview-ineligible>0</strong><span>不可处理</span></div></div><div class="bulk-preview-warning" data-bulk-preview-warning hidden></div><ul class="bulk-preview-items" data-bulk-preview-items></ul><div class="dialog-actions"><button class="button-secondary" type="button" data-bulk-preview-cancel>取消</button><button type="button" data-bulk-preview-confirm><svg class="icon" aria-hidden="true"><use href="#icon-check-circle"/></svg>确认应用</button></div></div>
    </div>
</dialog>
<dialog class="purge-dialog" data-purge-dialog aria-labelledby="purge-dialog-title" aria-describedby="purge-dialog-description">
    <div class="purge-dialog-content">
        <div class="purge-dialog-heading"><span class="section-icon" aria-hidden="true"><svg class="icon"><use href="#icon-trash"/></svg></span><div><h2 id="purge-dialog-title">永久删除链接？</h2><p id="purge-dialog-description">此操作无法撤销，请确认以下链接。</p></div></div>
        <strong class="purge-count" data-purge-count></strong>
        <ul class="purge-records" data-purge-records></ul>
        <div class="dialog-actions"><button class="button-secondary" type="button" data-purge-cancel autofocus>取消</button><button class="button-danger" type="button" data-purge-confirm><svg class="icon" aria-hidden="true"><use href="#icon-trash"/></svg>永久删除</button></div>
    </div>
</dialog>
<?php endif; ?>
<div id="copy-feedback" class="copy-feedback" role="status" aria-live="polite" hidden></div></body></html>
